### ISSUE TITLE
Failed to parse files

### ISSUE THREAD

**Issue by thecko** [blackcancer/StarOS#1]
I suppose it's due to the Universe update, but SMDecoder fails to parse total or partially the files. I've tested with the factions file and it extracts some info but it seems incorrect. When I try with a ship, directly does not show anything.

**Comment by blackcancer** [comment]
I'll work on this error quickly, the new update has change some part of file encoding i think too

**Comment by thecko** [comment]
It seems all the problem is in the line 188 of the file, this way seems to work (added the ord function call to $tag var)

```
while( ord($tag) != TAG_FINISH){
```

I'll do a Pull request later, I've only tested with ship, player and player state and I'm not sure it's ok. Also, I've not worked enough with the decoder to assure the extracted data is correct, I'll need you to check it.
